### PR TITLE
feat: HuggingFace Embedding Inference Server EF

### PR DESCRIPTION
**Pull request by tazarov**
- Go-version bump to 1.21 to support testcontainers

#50

### CODE REVIEW

**Comment by bjwswang** [comment]
> @bjwswang, I know I've bumped the go-version, but this seems to be required when using testcontainers. I've also noted that langchaingo also uses 1.21. Wdyt?

When langchaingo bumped golang to 1.21,I asked why . The author didn't make it(why go1.21) that clear.

**Comment by tazarov** [comment]
ok then, let's keep the bump to 1.21. It is unfortunate, but langchaingo is probably the largest user of the lib so we might as well go forward.

**Comment by bjwswang** [comment]
> ok then, let's keep the bump to 1.21. It is unfortunate, but langchaingo is probably the largest user of the lib so we might as well go forward.

that's right.

**Review by bjwswang — APPROVED** [review]
LGTM.

**Pull request merged**
